import { mkdir, writeFile, access, readFile } from "node:fs/promises";
import { constants } from "node:fs";
import { dirname, join } from "node:path";
import type { AITool, Answers } from "./types.js";
import { buildStackSection } from "./templates.js";

const STYLE_GUIDANCE: Record<Answers["codingStyle"], string> = {
  strict: "Strict mode. Types required. Lint clean. Tests for every public function. No `TODO` that ships.",
  pragmatic: "Ship readable code that works now. Add types and tests where they pay off, not prophylactically.",
  "fast-iteration":
    "Prototype mode. Optimize for speed of discovery. Mark throwaway code clearly with `// @throwaway`.",
};

const VERBOSITY_GUIDANCE: Record<Answers["verbosity"], string> = {
  terse: "Minimal commentary. Show code first, explain only when asked.",
  balanced: "Short explanations for non-obvious decisions. Skip narrating trivial changes.",
  "explain-more":
    "Explain the reasoning as you work. Call out tradeoffs and alternatives you considered.",
};

const TESTING_GUIDANCE: Record<Answers["testingEmphasis"], string> = {
  always: "Every new function or endpoint needs a test. No exceptions.",
  "critical-paths":
    "Test critical paths (auth, payments, data integrity, public APIs). Skip trivial getters/setters.",
  minimal: "Tests are welcome but not required for every change. Don't block shipping on coverage.",
};

const PROJECT_KIND_LABEL: Record<Answers["projectKind"], string> = {
  "web-app": "web application",
  api: "API / backend service",
  fullstack: "full-stack application",
  library: "library / SDK",
  cli: "command-line tool",
  mobile: "mobile application",
  other: "software project",
};

interface GeneratedFile {
  path: string;
  content: string;
}

function header(a: Answers): string {
  const lines: string[] = [];
  lines.push(`# ${a.projectName}`);
  lines.push("");
  if (a.description) lines.push(a.description);
  else lines.push(`A ${PROJECT_KIND_LABEL[a.projectKind]}.`);
  lines.push("");
  return lines.join("\n");
}

function coreBehavior(a: Answers): string {
  return [
    "## How to work in this repo",
    "",
    `- **Coding style**: ${STYLE_GUIDANCE[a.codingStyle]}`,
    `- **Verbosity**: ${VERBOSITY_GUIDANCE[a.verbosity]}`,
    `- **Testing**: ${TESTING_GUIDANCE[a.testingEmphasis]}`,
    "- **Scope discipline**: do what was asked — don't refactor adjacent code or add speculative abstractions.",
    "- **Before editing, read**: understand the file you're changing and its direct callers.",
    "- **Ask when ambiguous**: if a requirement is unclear, ask one clarifying question rather than guessing.",
  ].join("\n");
}

function stackBlock(a: Answers): string {
  const body = buildStackSection(a.stacks);
  if (!body) return "";
  return ["## Stack conventions", "", body].join("\n");
}

function customBlock(a: Answers): string {
  if (!a.customRules.trim()) return "";
  return ["## Project-specific rules", "", `- ${a.customRules.trim()}`].join("\n");
}

function generalGuardrails(): string {
  return [
    "## Guardrails",
    "",
    "- Never commit secrets, API keys, or credentials. If you spot one in a diff, stop and flag it.",
    "- Don't invent dependencies — if a package isn't already in the manifest, confirm before adding it.",
    "- When a command fails, read the actual error. Don't retry blindly or bypass with `--force`.",
    "- Prefer editing existing files over creating new ones.",
    "- If you touch public types, interfaces, or exported APIs, check every caller.",
  ].join("\n");
}

function assembleBody(a: Answers): string {
  return [header(a), coreBehavior(a), stackBlock(a), customBlock(a), generalGuardrails()]
    .filter((s) => s.trim().length > 0)
    .join("\n\n")
    .replace(/\n{3,}/g, "\n\n") + "\n";
}

function forCursor(body: string): string {
  return (
    `# .cursorrules\n` +
    `# Generated by contextarch — https://contextarch.ai\n\n` +
    `You are an expert pair programmer working in this repository. Follow the rules below precisely.\n\n` +
    body
  );
}

function forAgentsMd(body: string): string {
  return (
    `<!-- AGENTS.md — generated by contextarch — https://contextarch.ai -->\n\n` +
    body
  );
}

function forClaude(body: string): string {
  return (
    `<!-- CLAUDE.md — generated by contextarch — https://contextarch.ai -->\n\n` +
    body
  );
}

function forCopilot(body: string): string {
  return (
    `<!-- .github/copilot-instructions.md — generated by contextarch — https://contextarch.ai -->\n\n` +
    `These instructions apply to GitHub Copilot Chat in this repository.\n\n` +
    body
  );
}

export function buildFiles(a: Answers): GeneratedFile[] {
  const body = assembleBody(a);
  const out: GeneratedFile[] = [];
  const tools = new Set<AITool>(a.aiTools);

  if (tools.has("cursor")) out.push({ path: ".cursorrules", content: forCursor(body) });
  if (tools.has("windsurf")) out.push({ path: "AGENTS.md", content: forAgentsMd(body) });
  if (tools.has("claude-code")) out.push({ path: "CLAUDE.md", content: forClaude(body) });
  if (tools.has("copilot"))
    out.push({ path: ".github/copilot-instructions.md", content: forCopilot(body) });

  return out;
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await access(p, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

export interface WriteResult {
  path: string;
  wrote: boolean;
  skipped?: "exists";
  backupPath?: string;
}

export async function writeFiles(
  cwd: string,
  files: GeneratedFile[],
  opts: { overwrite: boolean; backup: boolean }
): Promise<WriteResult[]> {
  const results: WriteResult[] = [];

  for (const f of files) {
    const abs = join(cwd, f.path);
    const existed = await pathExists(abs);

    if (existed && !opts.overwrite) {
      results.push({ path: f.path, wrote: false, skipped: "exists" });
      continue;
    }

    await mkdir(dirname(abs), { recursive: true });

    let backupPath: string | undefined;
    if (existed && opts.backup) {
      backupPath = `${abs}.bak`;
      const prev = await readFile(abs, "utf8");
      await writeFile(backupPath, prev, "utf8");
    }

    await writeFile(abs, f.content, "utf8");
    results.push({ path: f.path, wrote: true, backupPath });
  }

  return results;
}
